
/* system header configure micro */

#define HAVE_ARPA_INET_H	1
#define HAVE_GETADDRINFO	1
#define HAVE_GETHOSTBYNAME	1
#define HAVE_INET_ADDR		1
#define HAVE_NETDB_H		1
#define HAVE_NETINET_IN_H	1
#define HAVE_SOCKET			1
#define HAVE_SYS_SOCKET_H	1
#define HAVE_SYS_TYPES_H	1
#define HAVE_UNISTD_H		1
#define USE_VECTOR			1
//#define ANSI_DECLARATORS	0
//#define HAVE_LIBZ			0
//#define HAVE_WINDOWS_H	0



/* proc setting micro */

#define PACKAGE_STRING "librcsc 4.1.0"
#define VERSION "4.1.0"

//#define ACTION_CHAIN_DEBUG
//#define ACTION_CHAIN_LOAD_DEBUG
//#define ASSUME_OPPONENT_KICK
//#define CREATE_SEVERAL_CANDIDATES_ON_SAME_POINT
//#define DEBUG
//#define DEBUG1
//#define DEBUG2
//#define DEBUG_CAN_SHOOT_FROM
//#define DEBUG_DIRECT_PASS
//#define DEBUG_EVALUATE
//#define DEBUG_LEADING_PASS
//#define DEBUG_PAINT_EVALUATED_POINTS
//#define DEBUG_PAINT_FAILED_COURSE
//#define DEBUG_PAINT_GRID_MAP
//#define DEBUG_PAINT_SUCCESS_COURSE
//#define DEBUG_PREDICT_OPPONENT_REACH_STEP
//#define DEBUG_PREDICT_OPPONENT_REACH_STEP_LEVEL2
//#define DEBUG_PREDICT_PLAYER_TURN_CYCLE
//#define DEBUG_PREDICT_RECEIVER
//#define DEBUG_PRINT
//#define DEBUG_PRINT_BALL_UPDATE
//#define DEBUG_PRINT_EVALUATE
//#define DEBUG_PRINT_FAILED_COURSE
//#define DEBUG_PRINT_FAILED_PASS
//#define DEBUG_PRINT_INTERCEPT_LIST
//#define DEBUG_PRINT_LEVEL_2
//#define DEBUG_PRINT_LINES
//#define DEBUG_PRINT_LONG_STEP
//#define DEBUG_PRINT_LONG_STEP_LEVEL_1
//#define DEBUG_PRINT_LONG_STEP_LEVEL_2
//#define DEBUG_PRINT_LONG_STEP_LEVEL_3
//#define DEBUG_PRINT_ONE_STEP
//#define DEBUG_PRINT_ONE_STEPy
//#define DEBUG_PRINT_OPPONENT
//#define DEBUG_PRINT_OPPONENT_LEVEL2
//#define DEBUG_PRINT_PARTICLE
//#define DEBUG_PRINT_PLAYER_RECORD
//#define DEBUG_PRINT_PLAYER_UPDATE
//#define DEBUG_PRINT_RECURSIVE
//#define DEBUG_PRINT_SELF_CACHE
//#define DEBUG_PRINT_SELF_UPDATE
//#define DEBUG_PRINT_SHAPE
//#define DEBUG_PRINT_SHORT_STEP
//#define DEBUG_PRINT_SIMULATE_DASHES
//#define DEBUG_PRINT_SUCCESS_COURSE
//#define DEBUG_PRINT_SUCCESS_PASS
//#define DEBUG_PRINT_TEXT
//#define DEBUG_PROFILE
//#define DEBUG_PROFILE_REMOVE
//#define DEBUG_THREE_STEP
//#define DEBUG_THROUGH_PASS
//#define DEBUG_UPDATE_OPPONENT
//#define DEBUG_UPDATE_PASSER
//#define DEBUG_UPDATE_RECEIVERS
//#define DO_MONTECARLO_SEARCH
//#define OLD_DIR_ROUND
//#define PROFILE_SEE
//#define SEARCH_UNTIL_MAX_SPEED_AT_SAME_POINT
//#define SELF_INTERCEPT_USE_NO_SAVE_RECEVERY
//#define STRICT_LINE_UPDATE
//#define TRIANGULATION_STRICT_POINT_SET
//#define USE_ADJUST_DASH
//#define USE_CHANGE_VIEW
//#define USE_GENERIC_FACTORY
//#define USE_GOALIE_MODE
//#define USE_LIST_VISUAL_OBJECT
//#define USE_OMNI_DASH
//#define USE_ONLY_MAX_ANGLE_WIDTH
//#define USE_VIEW_GRID_MAP


